### ISSUE TITLE
AlertDialog from support-v7 library

### ISSUE THREAD

**Issue by johnjohndoe** [cketti/ckChangeLog#30]
Are you planning to switch to the [android.support.v7.app.AlertDialog](http://developer.android.com/reference/android/support/v7/app/AlertDialog.html) which supports defining an **accent color**, including pre-Lollipop Android versions?

You would need to replace the [import](https://github.com/cketti/ckChangeLog/blob/v1.2.2/ckChangeLog/src/main/java/de/cketti/library/changelog/ChangeLog.java#L45) for the [AlertDialog](https://github.com/cketti/ckChangeLog/blob/v1.2.2/ckChangeLog/src/main/java/de/cketti/library/changelog/ChangeLog.java#L291) and reference a style for it:

``` java
AlertDialog.Builder builder = new AlertDialog.Builder(mContext, R.style.AppDialog);
```
The *styles.xml* cool look like this:

``` xml
<style name="AppDialog" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="colorAccent">@color/accent</item>
</style>
```

**Comment by mgursch** [comment]
+1

**Comment by cketti** [comment]
No. As explained [in my comment to pull request #32](https://github.com/cketti/ckChangeLog/pull/32#issuecomment-109798196) my plan is to reduce the library to just the core functionality. Once that's done it should be easy to use it with your own UI code, e.g. the `AlertDialog` class from the support library.

**Comment by smichel17** [comment]
I'd like to put in a word in favor of keeping the dialog; the reason I'm using this library is how easy it was to add: a whopping three lines of code (plus the changelog itself, obviously).
```
// build.gradle
compile 'de.cketti.library.changelog:ckchangelog:1.2.2'

// MainActivity.kt
import de.cketti.library.changelog.ChangeLog
ChangeLog(this).run { if (isFirstRun) logDialog.show() } // shorter because Kotlin
```

When looking for a changelog library, because of #40, I decided not to use this one, and go with [this](https://github.com/gabrielemariotti/changeloglib) instead. But after around 20 minutes of trying to figure out how to display it correctly, I decided it just wasn't worth wrestling with, and came back here (5 min setup, if that). A changelog is a really functional thing. It doesn't need to be perfect, it just needs to be good and easy enough.

Obviously it's possible to break out a lib that does just the text, while maintaining one that provides a dialog.

**Comment by smichel17** [comment]
The other changelog option I almost went with was: just write it in markdown, and display that in a dialogue as plain text (always display the full changelog).
